// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonAdd: typeof import('~icons/carbon/add')['default']
    CarbonArrowDownRight: typeof import('~icons/carbon/arrow-down-right')['default']
    CarbonArrowRight: typeof import('~icons/carbon/arrow-right')['default']
    CarbonCalendar: typeof import('~icons/carbon/calendar')['default']
    CarbonColorPalette: typeof import('~icons/carbon/color-palette')['default']
    CarbonGift: typeof import('~icons/carbon/gift')['default']
    CarbonPedestrianChild: typeof import('~icons/carbon/pedestrian-child')['default']
    CarbonSettings: typeof import('~icons/carbon/settings')['default']
    CarbonStar: typeof import('~icons/carbon/star')['default']
    CarbonTask: typeof import('~icons/carbon/task')['default']
    CarbonUserFollow: typeof import('~icons/carbon/user-follow')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
