// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonAdd: typeof import('~icons/carbon/add')['default']
    CarbonArrowDownRight: typeof import('~icons/carbon/arrow-down-right')['default']
    CarbonCalendar: typeof import('~icons/carbon/calendar')['default']
    CarbonChevronRight: typeof import('~icons/carbon/chevron-right')['default']
    CarbonColorPalette: typeof import('~icons/carbon/color-palette')['default']
    CarbonEdit: typeof import('~icons/carbon/edit')['default']
    CarbonGift: typeof import('~icons/carbon/gift')['default']
    CarbonOverflowMenuVertical: typeof import('~icons/carbon/overflow-menu-vertical')['default']
    CarbonPedestrianChild: typeof import('~icons/carbon/pedestrian-child')['default']
    CarbonSettings: typeof import('~icons/carbon/settings')['default']
    CarbonStar: typeof import('~icons/carbon/star')['default']
    CarbonTouch1: typeof import('~icons/carbon/touch1')['default']
    CarbonTrashCan: typeof import('~icons/carbon/trash-can')['default']
    CarbonUserFollow: typeof import('~icons/carbon/user-follow')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    ProfileForm: typeof import('./components/ProfileForm.vue')['default']
    README: typeof import('./components/README.md')['default']
    RewardForm: typeof import('./components/RewardForm.vue')['default']
    TaskForm: typeof import('./components/TaskForm.vue')['default']
  }
}

export { }
