// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActiveUserAvatar: typeof import('./components/ActiveUserAvatar.vue')['default']
    CarbonChevronRight: typeof import('~icons/carbon/chevron-right')['default']
    CarbonGift: typeof import('~icons/carbon/gift')['default']
    CarbonHome: typeof import('~icons/carbon/home')['default']
    DefaultAvatar: typeof import('./components/DefaultAvatar.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    LastUpdated: typeof import('./components/LastUpdated.vue')['default']
    ProfileForm: typeof import('./components/ProfileForm.vue')['default']
    ProfileMenu: typeof import('./components/ProfileMenu.vue')['default']
    README: typeof import('./components/README.md')['default']
    RewardForm: typeof import('./components/RewardForm.vue')['default']
    RewardList: typeof import('./components/RewardList.vue')['default']
    RewardProgress: typeof import('./components/RewardProgress.vue')['default']
    TaskForm: typeof import('./components/TaskForm.vue')['default']
  }
}

export { }
